'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),{EventEmitter}=require('node:events');
const core=require('../core.cjs');
const disk={device:'/dev/fixture-usb',serial:'SYNTHETIC-SERIAL',size:1024**3,model:'Fixture USB',eligible:true};
function capsule(){return {schema:1,hostname:'aguja-fixture',locale:{language:'es_CO.UTF-8',keyboard:'latam',variant:'nodeadkeys'},network:{ethernet:{method:'auto'},wifi:{ssid:'',password:'',security:'wpa-psk',country:'ES',hidden:false}},ssh:{password:'fixture-only',public_key:'',port:22},providers:{},remote:{enabled:false}};}
function harness({answer=1,claimAnswer=1,claimStatus=200,changeAccountAt='',allowSave=false,saveCanceled=false,backupCanceled=false,changedAt=0,preparedSize=24,initialDisk=disk,writerCode=0,writerError=null,splitOutputUtf8=false,accountUser=null,remoteFixture=null,expireDuringConfirmation=false,platform=process.platform}={}) {
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'aguja-flash-mock-')),image=path.join(temp,'public.img');fs.writeFileSync(image,'synthetic-public-image');
 const calls=[],handlers={},webContents={mainFrame:{},send(){}};let checks=0;
 const dialogs={showMessageBox:async(win,options)=>{const claim=options.title==='Vincular túnel anterior';calls.push({kind:claim?'claim-confirmation':'confirmation',options});if(expireDuringConfirmation&&remoteFixture)remoteFixture.expiresAt=1;if(claim&&changeAccountAt==='confirmation')context.fixtureUser={id:'changed-owner',email:'changed@example.invalid',emailVerified:true};return {response:claim?claimAnswer:answer};},showOpenDialog:async()=>{calls.push({kind:'backup-choice'});return {canceled:backupCanceled,filePaths:[temp]};},showSaveDialog:async()=>{if(!allowSave)throw Error('Auto flash must never request image Save As');calls.push({kind:'save-choice'});return {canceled:saveCanceled,filePath:path.join(temp,'saved-private.img')};}};
 const app={isPackaged:false,getPath:()=>temp,getVersion:()=> 'fixture',whenReady:()=>({then(){}}),on(){}};
 function spawn(command,args){const proc=new EventEmitter();proc.stdout=new EventEmitter();proc.stderr=new EventEmitter();proc.kill=()=>{};proc.stdin=new EventEmitter();proc.stdin.end=input=>setImmediate(()=>{
  try{
   let out='';
   if(command==='/usr/bin/lsblk'){checks++;const d=checks===changedAt?{...initialDisk,size:initialDisk.size+1}:initialDisk;out=JSON.stringify({blockdevices:[{path:d.device,type:'disk',tran:'usb',rm:true,serial:d.serial,size:d.size,model:d.model,mountpoints:[]}]});calls.push({kind:'disk-check'});}
   else if(command==='/usr/bin/python3'){const data=JSON.parse(input);assert.equal(data.op,'prepare');calls.push({kind:'prepare',data});fs.writeFileSync(data.output_path,Buffer.alloc(preparedSize,42),{mode:0o600});out=JSON.stringify({ok:true,sha256:crypto.createHash('sha256').update(fs.readFileSync(data.output_path)).digest('hex')});}
   else if(command==='/usr/bin/pkexec'){calls.push({kind:'flash',args});out=JSON.stringify(writerError?{ok:false,error:writerError}:{ok:true,verified:true,backup_verified:args.includes('--backup-dir')});}
   else throw Error('Unexpected command '+command);
   const bytes=Buffer.from(out);if(splitOutputUtf8){const lead=bytes.indexOf(0xc3);if(lead>=0){proc.stdout.emit('data',bytes.subarray(0,lead+1));proc.stdout.emit('data',bytes.subarray(lead+1));}else proc.stdout.emit('data',bytes);}else proc.stdout.emit('data',bytes);proc.emit('close',command==='/usr/bin/pkexec'?writerCode:0);
  }catch(e){proc.emit('error',e);}
 });return proc;}
 const context={require:name=>name==='electron'?{app,BrowserWindow:function(){},ipcMain:{handle:(channel,callback)=>handlers[channel]=callback},dialog:dialogs,clipboard:{}}:name==='node:child_process'?{spawn}:name==='./ai-tools.cjs'?require('../ai-tools.cjs'):name==='./provisioning.cjs'?require('../provisioning.cjs'):name==='./windows-flash.cjs'?require('../windows-flash.cjs'):name==='./core.cjs'?core:name==='./ui/i18n.js'?require('../ui/i18n.js'):name==='./bitlocker.cjs'?require('../bitlocker.cjs'):name==='./fat32-writer.cjs'?require('../fat32-writer.cjs'):name.startsWith('./')?require(path.resolve(__dirname,'..',name)):require(name),__dirname:path.resolve(__dirname,'..'),process:{...process,platform},Buffer,URL,fetch,AbortSignal,Response,setTimeout,clearTimeout,structuredClone,fakeWindow:{webContents,isDestroyed:()=>false},initialImage:{path:image,sha256:crypto.createHash('sha256').update(fs.readFileSync(image)).digest('hex'),bytes:fs.statSync(image).size}};
 vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../main.cjs'),'utf8')+'\nwin=fakeWindow;selectedImage=initialImage;installIPC();',context);
 const invoke=(channel,input)=>handlers[channel]({sender:webContents,senderFrame:webContents.mainFrame},input);
 const roundtrip=c=>{context.roundtripCapsule=c;return JSON.parse(JSON.stringify(vm.runInContext('profileDecrypt(profileEncrypt(roundtripCapsule,"fixture-profile-password"),"fixture-profile-password")',context)));};
 const seedPrepared=input=>{context.fixtureInput=input;context.fixturePrivate=path.join(temp,'prepared-before-dialog.img');fs.writeFileSync(context.fixturePrivate,Buffer.alloc(preparedSize,42));vm.runInContext('prepared={path:fixturePrivate,...initialImage,bytes:'+preparedSize+',fingerprint:prepareInput(fixtureInput).fingerprint};prepared.path=fixturePrivate;',context);};
 return {temp,handlers,calls,invoke,roundtrip,seedPrepared,input:{device:disk.device,serial:disk.serial,backup:false,capsule:capsule(),protection:{mode:'plain'}},close:()=>fs.rmSync(temp,{recursive:true,force:true})};
}
test('one native confirmation prepares private image automatically and passes only backend-generated FLASH receipt',async()=>{
 const h=harness();try{const result=await h.invoke('flash',h.input);assert.equal(result.ok,true);assert.equal(result.verified,true);assert(result.prepared);const sequence=h.calls.map(x=>x.kind);assert.deepEqual(sequence,['disk-check','confirmation','disk-check','prepare','disk-check','flash']);
 const prepared=h.calls.find(x=>x.kind==='prepare').data;assert(prepared.output_path.startsWith(path.join(h.temp,'private-images')));assert.equal(fs.statSync(path.dirname(prepared.output_path)).mode&0o777,0o700);assert.equal(fs.statSync(prepared.output_path).mode&0o777,0o600);assert.deepEqual(prepared.capsule.locale,capsule().locale);
 const flash=h.calls.find(x=>x.kind==='flash').args;assert.equal(flash[flash.indexOf('--confirm')+1],'FLASH:'+disk.serial);assert(!flash.includes('--backup-dir'));assert(flash.includes('--report-dir'));assert.equal(result.backupVerified,false);assert(!h.calls.some(x=>x.kind==='backup-choice'));const confirmation=h.calls.find(x=>x.kind==='confirmation').options;for(const value of [disk.model,disk.serial,disk.device,'GiB'])assert(confirmation.detail.includes(value));assert.equal(confirmation.defaultId,0);
 }finally{h.close();}
});
for(const [name,options]of [['native confirmation',{answer:0}],['backup selection',{backupCanceled:true}]])test('canceling '+name+' does not prepare or write anything',async()=>{const h=harness(options);try{const r=await h.invoke('flash',{...h.input,backup:true});assert.equal(r.ok,true);assert.equal(r.canceled,true);assert(!h.calls.some(x=>['prepare','flash'].includes(x.kind)));assert(!fs.existsSync(path.join(h.temp,'private-images')));}finally{h.close();}});
for(const [name,options]of [['before preparation',{changedAt:2}],['after preparation',{changedAt:3}],['image exceeds capacity',{preparedSize:24,initialDisk:{...disk,size:23}}]])test('USB changed '+name+' cannot reach privileged writer',async()=>{const h=harness(options);try{const r=await h.invoke('flash',h.input);assert.equal(r.ok,false);assert(!h.calls.some(x=>x.kind==='flash'));}finally{h.close();}});
test('invalid settings and missing exact USB identity fail before native confirmation',async()=>{const h=harness();try{let r=await h.invoke('flash',{...h.input,capsule:{...h.input.capsule,locale:{language:'unsafe',keyboard:'es',variant:''}}});assert.equal(r.ok,false);r=await h.invoke('flash',{...h.input,serial:'WRONG'});assert.equal(r.ok,false);assert(!h.calls.some(x=>x.kind==='confirmation'));}finally{h.close();}});
test('encrypted profile retains locale selections through real main encryption/decryption',async()=>{const h=harness();try{const restored=h.roundtrip(h.input.capsule);assert.deepEqual(restored.locale,h.input.capsule.locale);assert.equal(restored.ssh.password,h.input.capsule.ssh.password);}finally{h.close();}});

test('optional backup explicitly opens destination and reaches writer with backup flag',async()=>{const h=harness();try{const r=await h.invoke('flash',{...h.input,backup:true});assert.equal(r.ok,true);assert.equal(r.backupVerified,true);assert(h.calls.some(x=>x.kind==='backup-choice'));const args=h.calls.find(x=>x.kind==='flash').args;assert.equal(args[args.indexOf('--backup-dir')+1],h.temp);}finally{h.close();}});
test('writer failure is displayed precisely and is not reported as success',async()=>{const h=harness({writerCode:1,writerError:'La imagen cambió antes de grabar; no se escribe el USB'});try{const r=await h.invoke('flash',h.input);assert.equal(r.ok,false);assert.equal(r.error,'La imagen cambió antes de grabar; no se escribe el USB');}finally{h.close();}});
test('polkit cancellation gives a permissions message without exposing stderr',async()=>{const h=harness({writerCode:126});try{const r=await h.invoke('flash',h.input);assert.equal(r.ok,false);assert(r.error.includes('permisos de Linux'));}finally{h.close();}});

for(const channel of ['prepare','flash'])for(const saved of [null,{base:'https://aguja.transcendenceia.net',accountId:'other-owner',expiresAt:Date.now()+3600000,device:{device_id:'d'.repeat(22),device_token:'SYNTHETIC-OLD-DEVICE'}},{base:'https://fixture.invalid',ownerToken:'SYNTHETIC-LEGACY-OWNER',expiresAt:Date.now()+3600000,device:{device_id:'l'.repeat(22),device_token:'SYNTHETIC-LEGACY-DEVICE'}}])test(channel+' ignores legacy relay opt-in without enrolling/claiming or copying saved secrets ('+(saved?.accountId||saved?.base||'no session')+')',async()=>{
 const h=harness({allowSave:true,accountUser:{id:'owner',emailVerified:true},remoteFixture:saved});try{const input=structuredClone(h.input);input.capsule.remote={enabled:true,relay_url:'old-invalid-relay',ttl_seconds:3600,device_token:'SYNTHETIC-INJECTED-DEVICE'};input.capsule.account={token:'SYNTHETIC-ACCOUNT-NEVER-USB'};input.capsule.ssh.account_token='SYNTHETIC-ACCOUNT-NEVER-USB';const r=await h.invoke(channel,input);assert.equal(r.ok,true);assert(!h.calls.some(c=>['remote-request','claim-confirmation'].includes(c.kind)));const prepared=h.calls.find(c=>c.kind==='prepare').data.capsule;assert.deepEqual(prepared.remote,{enabled:false});for(const fragment of ['SYNTHETIC-OLD','SYNTHETIC-LEGACY','SYNTHETIC-INJECTED','NEVER-USB'])assert(!JSON.stringify(prepared).includes(fragment));assert(!fs.existsSync(path.join(h.temp,'remote-session.private.json')));}finally{h.close();}
});
test('tailnet preparation is independent of download account and never enrolls from the Imager',async()=>{const h=harness();try{const input=structuredClone(h.input);input.capsule.tailscale={enabled:true,auth_key:'SYNTHETIC-TAILNET-KEY',login_server:'https://fixture.invalid',hostname:'rescue-fixture',ssh:false,accept_routes:false};const result=await h.invoke('flash',input);assert.equal(result.ok,true);const prepared=h.calls.find(c=>c.kind==='prepare').data.capsule;assert.equal(prepared.tailscale.auth_key,'SYNTHETIC-TAILNET-KEY');assert.equal(prepared.tailscale.ssh,false);assert(!JSON.stringify(result).includes('SYNTHETIC-TAILNET-KEY'));assert(!JSON.stringify(h.calls.find(c=>c.kind==='confirmation')).includes('SYNTHETIC-TAILNET-KEY'));assert(!h.calls.some(c=>c.kind==='remote-request'));}finally{h.close();}});
test('tailnet enabled profile roundtrips through real desktop encryption while injected credentials are removed',()=>{const h=harness();try{const c=structuredClone(h.input.capsule);c.account={token:'SYNTHETIC-ACCOUNT-NEVER-PROFILE'};c.remote={enabled:true,device_token:'SYNTHETIC-DEVICE-NEVER-PROFILE'};c.tailscale={enabled:true,auth_key:'SYNTHETIC-TAILNET-KEY',login_server:'',hostname:'',session_token:'SYNTHETIC-ACCOUNT-NEVER-PROFILE'};const restored=h.roundtrip(c);assert.equal(restored.tailscale.auth_key,c.tailscale.auth_key);assert.equal(restored.tailscale.ssh,false);assert.equal(restored.tailscale.accept_routes,false);assert(!JSON.stringify(restored).includes('NEVER-PROFILE'));assert.deepEqual(restored.remote,{enabled:false});}finally{h.close();}});
test('disabled tailnet strips stale key and injected data from reusable encrypted profile',()=>{const h=harness();try{const c=structuredClone(h.input.capsule);c.tailscale={enabled:false,auth_key:'SYNTHETIC-NEVER-PROFILE',hostname:'old-node',device_token:'SYNTHETIC-NEVER-PROFILE'};const restored=h.roundtrip(c);assert.deepEqual(restored.tailscale,{enabled:false});assert(!JSON.stringify(restored).includes('NEVER-PROFILE'));}finally{h.close();}});
test('retired relay and account IPC channels are absent',()=>{const h=harness();try{for(const channel of ['remote-pair','remote-share','account-start','agent-export'])assert.equal(h.handlers[channel],undefined);}finally{h.close();}});

test('Windows refuses requested backup before confirmation, preparation or writing',async()=>{const h=harness({platform:'win32'});try{const result=await h.invoke('flash',{...h.input,backup:true});assert.equal(result.ok,false);assert.match(result.error,/respaldo.*Windows/);assert.equal(h.calls.length,0);}finally{h.close();}});

test('native writer UTF-8 error survives a character split across pipe data chunks',async()=>{const error='La imagen cambió antes de grabar; no se escribe el USB',h=harness({writerCode:1,writerError:error,splitOutputUtf8:true});try{const r=await h.invoke('flash',h.input);assert.equal(r.ok,false);assert.equal(r.error,error);}finally{h.close();}});
