'use strict';
const {_electron:electron}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
(async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'aguja-usb-ui-')),image=path.join(temp,'fixture.img'),bootstrap=path.join(temp,'bootstrap.cjs'),main=path.resolve(__dirname,'../main.cjs');let app;
 fs.writeFileSync(image,'synthetic image for mocked helper only');
 fs.writeFileSync(bootstrap,`
 const fs=require('node:fs'),crypto=require('node:crypto'),{EventEmitter}=require('node:events'),electron=require('electron');
 globalThis.flashFixture={answer:0,backupCanceled:false,calls:[]};
 const state=globalThis.flashFixture;
 const disk={path:'/dev/fixture-usb',type:'disk',tran:'usb',rm:true,serial:'FIXTURE-USB',size:1024**3,model:'Synthetic USB',mountpoints:[]};
 require('node:child_process').spawn=(command,args)=>{const proc=new EventEmitter();proc.stdout=new EventEmitter();proc.stderr=new EventEmitter();proc.stdin=new EventEmitter();proc.kill=()=>{};proc.stdin.end=input=>setImmediate(()=>{try{let out='';if(command==='/usr/bin/lsblk')out=JSON.stringify({blockdevices:[disk]});else if(command==='/usr/bin/python3'){const d=JSON.parse(input);if(d.op!=='prepare')throw Error('Unexpected op');state.calls.push({kind:'prepare',locale:d.capsule.locale});fs.writeFileSync(d.output_path,'synthetic private image',{mode:0o600});out=JSON.stringify({ok:true,sha256:crypto.createHash('sha256').update('synthetic private image').digest('hex')});}else if(command==='/usr/bin/pkexec'){state.calls.push({kind:'flash',confirm:args[args.indexOf('--confirm')+1],backup:args.includes('--backup-dir')});out=JSON.stringify({ok:true,verified:true,backup_verified:args.includes('--backup-dir')});}else throw Error('Unexpected command');proc.stdout.emit('data',Buffer.from(out));proc.emit('close',0);}catch(e){proc.emit('error',e);}});return proc;};
 electron.dialog.showMessageBox=async(w,o)=>{state.calls.push({kind:'confirm',detail:o.detail});return {response:state.answer};};
 electron.dialog.showOpenDialog=async(w,o)=>o.properties.includes('openFile')?{canceled:false,filePaths:[${JSON.stringify(image)}]}:{canceled:state.backupCanceled,filePaths:[${JSON.stringify(temp)}]};
 electron.dialog.showSaveDialog=async()=>{throw Error('Auto flash must not show Save As');};
 require(${JSON.stringify(path.resolve(__dirname,'../core.cjs'))}).getHTTPS=async()=>{throw Error('Synthetic offline fixture');};
 require(${JSON.stringify(main)});
 `);
 try{
 app=await electron.launch({args:[bootstrap,'--lang=es','--no-sandbox','--user-data-dir='+path.join(temp,'state')],env:{...process.env,ELECTRON_DISABLE_SECURITY_WARNINGS:'1'}});const w=await app.firstWindow();await w.waitForLoadState('domcontentloaded');await w.locator('#image-import').click();await w.locator('#image-status').waitFor();
 await w.locator('.step').nth(1).click();await w.locator('#locale-language').selectOption('es_CO.UTF-8');await w.locator('#locale-keyboard').selectOption('latam');await w.locator('#locale-variant').selectOption('nodeadkeys');
 await w.locator('.step').nth(5).click();assert(await w.locator('#flash').isDisabled());await w.locator('#disks-refresh').click();await w.locator('#usb-disks option[value="0"]').waitFor({state:'attached'});await w.locator('#usb-disks').selectOption('0');assert.equal(await w.locator('#flash').isEnabled(),true);assert.equal(await w.locator('#usb-confirm').count(),0);assert.equal(await w.locator('#usb-backup').isChecked(),false);assert((await w.locator('#flash-status').textContent()).includes('prepararemos'));
 await w.locator('#flash').click();await w.waitForFunction(()=>!document.querySelector('#flash').disabled);let state=await app.evaluate(()=>globalThis.flashFixture);assert.equal(state.calls.filter(x=>x.kind==='prepare').length,0);assert.equal(state.calls.filter(x=>x.kind==='flash').length,0);
 await app.evaluate(()=>{globalThis.flashFixture.answer=1;});await w.locator('#flash').click();await w.locator('#notification.success').filter({hasText:'USB grabado'}).waitFor();state=await app.evaluate(()=>globalThis.flashFixture);assert.equal(state.calls.filter(x=>x.kind==='prepare').length,1);assert.equal(state.calls.filter(x=>x.kind==='flash').length,1);assert.deepEqual(state.calls.find(x=>x.kind==='prepare').locale,{language:'es_CO.UTF-8',keyboard:'latam',variant:'nodeadkeys'});assert.equal(state.calls.find(x=>x.kind==='flash').confirm,'FLASH:FIXTURE-USB');assert.equal(state.calls.find(x=>x.kind==='flash').backup,false);assert((await w.locator('#notification').textContent()).includes('sin respaldo'));
 await w.locator('.step').nth(1).click();await w.locator('#locale-keyboard').selectOption('us');await w.locator('#locale-variant').selectOption('intl');await w.locator('.step').nth(5).click();assert.equal(await w.locator('#flash').isEnabled(),true);assert((await w.locator('#prepared-status').textContent()).includes('se preparará de nuevo'));
 await w.locator('#usb-backup').check();await w.locator('#flash').click();await w.locator('#notification.success').filter({hasText:'USB grabado'}).waitFor();state=await app.evaluate(()=>globalThis.flashFixture);assert.equal(state.calls.filter(x=>x.kind==='prepare').length,2);assert.equal(state.calls.filter(x=>x.kind==='flash').length,2);assert.deepEqual(state.calls.filter(x=>x.kind==='prepare').at(-1).locale,{language:'es_CO.UTF-8',keyboard:'us',variant:'intl'});
 assert.equal(state.calls.filter(x=>x.kind==='flash').at(-1).backup,true);assert((await w.locator('#notification').textContent()).includes('respaldo anterior'));
 console.log(JSON.stringify({ok:true,directDefault:true,optionalBackup:true,realElectron:true,automaticPreparation:true,nativeCancelNoWrites:true,configurationInvalidationReprepares:true,physicalUsbWritten:false,mockedPrivilegeOnly:true}));
 }finally{if(app)await app.close();fs.rmSync(temp,{recursive:true,force:true});}
})().catch(error=>{console.error('USB UI fixture verification failed: '+error.message);process.exitCode=1;});
