'use strict';
// Browser-only renderer contracts, no accounts, network or USB operations.
const assert=require('node:assert/strict'),path=require('node:path');const {chromium}=require('playwright');const catalog=require('../../runtime/locale-catalog.json');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.AGUJA_QA_BROWSER||'/usr/bin/chromium'});try{const page=await browser.newPage({viewport:{width:1240,height:880},locale:'en-US'});
 await page.addInitScript(({catalog})=>{const success=async()=>({ok:true});window.aguja={i18nCatalog:async()=>({ok:true,catalog,language:'en-US',systemLanguage:'en-US'}),i18nLanguage:success,info:async()=>({ok:true,version:'synthetic'}),providerStatus:async()=>({ok:true,providers:{}}),invalidatePrepared:success,onProgress:callback=>{window.__progress=callback;}};},{catalog});
 await page.goto('file://'+path.resolve(__dirname,'../ui/index.html'));await page.locator('h1').first().waitFor();
 assert.equal(await page.locator('html').getAttribute('lang'),'en');assert.equal(await page.locator('#account-card, #remote-enabled, #agent-access').count(),0);
 await page.locator('.step').nth(1).click();await page.locator('#wifi-password').fill('SYNTHETIC-SECRET-KEEP-EXACT');await page.locator('#wifi-ssid').fill('Iniciar sesión');await page.locator('#locale-language').selectOption('zh_CN.UTF-8');await page.locator('#locale-keyboard').selectOption('cn');assert.equal(await page.locator('#locale-variant option').count(),1);
 await page.locator('#app-language').selectOption('zh');await page.waitForFunction(()=>document.documentElement.lang==='zh');assert.equal(await page.locator('#wifi-password').inputValue(),'SYNTHETIC-SECRET-KEEP-EXACT');assert.equal(await page.locator('#wifi-password').getAttribute('type'),'password');assert.equal(await page.locator('#wifi-ssid').inputValue(),'Iniciar sesión');assert.equal(await page.locator('#locale-language').inputValue(),'zh_CN.UTF-8');assert.equal(await page.locator('#locale-keyboard').inputValue(),'cn');
 await page.locator('.step').nth(0).click();assert((await page.locator('h1').first().textContent()).includes('你的 LA AGUJA'));assert.equal(await page.locator('.brand b').textContent(),'LA AGUJA');assert.equal(await page.title(),'LA AGUJA 镜像写入工具');
 await page.locator('.step').nth(4).click();assert.equal(await page.locator('#remote-enabled').isVisible(),false);await page.locator('#tailscale-enabled').check();assert.equal(await page.locator('#tailscale-fields').isVisible(),true);assert.equal(await page.locator('#tailscale-ssh').isChecked(),false);await page.locator('#tailscale-enabled').uncheck();assert.equal(await page.locator('#tailscale-fields').isVisible(),false);assert.equal(await page.locator('#remote-fields').count(),0);
 await page.locator('#app-language').selectOption('en');await page.waitForFunction(()=>document.documentElement.lang==='en');assert.equal(await page.locator('#wifi-password').inputValue(),'SYNTHETIC-SECRET-KEEP-EXACT');assert.equal(await page.locator('#account-card, #remote-enabled, #agent-access').count(),0);assert.equal(await page.locator('#locale-language').inputValue(),'zh_CN.UTF-8');assert.equal(await page.locator('#locale-keyboard').inputValue(),'cn');
 await page.locator('.step').nth(1).click();await page.locator('#locale-keyboard').selectOption('us');await page.locator('#locale-variant').selectOption('intl');await page.locator('#locale-keyboard').selectOption('cn');assert.equal(await page.locator('#locale-variant').inputValue(),'');
 for(const locale of catalog.uiLanguages){await page.locator('#app-language').selectOption(locale.value);await page.waitForFunction(code=>document.documentElement.lang===code,locale.value);for(let step=0;step<6;step++){await page.locator('.step').nth(step).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${locale.value} step ${step} overflow`);}}
 console.log(JSON.stringify({ok:true,rendererBrowser:true,languages:catalog.uiLanguages.map(l=>l.value),secretPreserved:true,publicWithoutAccount:true,physicalUsbWritten:false}));
 }finally{await browser.close();}})().catch(error=>{console.error(error.stack);process.exitCode=1;});
