'use strict';
// Cross-runtime contract proof: native Windows JS capsule -> exact runtime Python reader.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const provisioning=require('../provisioning.cjs'),fat=require('../fat32-writer.cjs');
const py='/usr/bin/python3';
function capsule(){return {schema:1,hostname:'aguja-fixture',locale:{language:'es_CO.UTF-8',keyboard:'latam',variant:'nodeadkeys'},network:{ethernet:{method:'auto'},wifi:{ssid:'Fixture',password:'SYNTHETIC-WIFI',security:'wpa-psk',country:'ES',hidden:false}},ssh:{password:'SYNTHETIC-SSH',public_key:'',port:22},providers:{codex:{mode:'api',api_key:'SYNTHETIC-API',base_url:'',model:''}},remote:{enabled:false}};}
for(const mode of ['plain','encrypted'])test('Windows '+mode+' envelope opens in real Aguja Python runtime', {skip:process.platform==='win32'},()=>{
 const protection={mode,passphrase:'SYNTHETIC-UNLOCK'},raw=provisioning.seal(capsule(),protection);if(mode==='encrypted')assert(!raw.includes('SYNTHETIC-API'));
 const script='import sys,json;sys.path.insert(0,sys.argv[1]);from profile import open_capsule; c=open_capsule(sys.stdin.buffer.read(),"SYNTHETIC-UNLOCK");assert c["providers"]["codex"]["api_key"]=="SYNTHETIC-API";assert c["network"]["wifi"]["password"]=="SYNTHETIC-WIFI";print("opened")';assert.equal(execFileSync(py,['-I','-c',script,path.resolve(__dirname,'../../runtime')],{input:raw}).toString().trim(),'opened');
});
function synthetic(dir,{tailnet=true}={}){const image=path.join(dir,'factory.img'),part=path.join(dir,'cfg.fat');fs.writeFileSync(image,'');fs.truncateSync(image,96*1024**2);execFileSync('/usr/sbin/sgdisk',['-o','-n','1:2048:+64M','-t','1:0700','-c','1:AGUJA_CFG',image],{stdio:'pipe'});fs.writeFileSync(part,'');fs.truncateSync(part,64*1024**2);execFileSync('/usr/sbin/mkfs.vfat',['-F','32','-n','AGUJA_CFG',part],{stdio:'pipe'});const fd=fs.openSync(image,'r+'),b=fs.readFileSync(part);fs.writeSync(fd,b,0,b.length,1048576);fs.closeSync(fd);fat.writeFat32File(image,'AGUJA_CFG','release.json',JSON.stringify({features:['platform-profile-v1','locale-profile-v1','locale-preunlock-v1','antigravity-oauth-file-v1','i18n-catalog-v1',...(tailnet?['tailscale-profile-v1']:[])]}));return image;}
test('Windows image uses real long filenames, external mtools reads profile, replacement frees old clusters', {skip:process.platform==='win32'},async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),"aguja win á ' & "));try{
 const source=synthetic(dir),output=path.join(dir,'personal.img'),digest=crypto.createHash('sha256').update(fs.readFileSync(source)).digest('hex');await provisioning.prepareWindows({source,output,sha256:digest,capsule:capsule(),protection:{mode:'encrypted',passphrase:'SYNTHETIC-UNLOCK'}});assert.equal(crypto.createHash('sha256').update(fs.readFileSync(source)).digest('hex'),digest);
 const readback=path.join(dir,'readback.json');execFileSync('mcopy',['-i',output+'@@1048576','::/aguja-profile.json',readback]);assert.equal(JSON.parse(fs.readFileSync(readback)).protection,'encrypted');const opened=execFileSync(py,['-I','-c','import sys;sys.path.insert(0,sys.argv[1]);from profile import open_capsule;assert open_capsule(open(sys.argv[2],"rb").read(),"SYNTHETIC-UNLOCK")["hostname"]=="aguja-fixture";print("opened")',path.resolve(__dirname,'../../runtime'),readback]);assert.equal(opened.toString().trim(),'opened');
 const first=fat.writeFat32File(output,'AGUJA_CFG','aguja-profile.json',Buffer.alloc(1200,42));const second=fat.writeFat32File(output,'AGUJA_CFG','aguja-profile.json','replacement');const fd=fs.openSync(output,'r');try{const part=fat.findGptPartition(fd),params=fat.parseFat32Params(fd,part.offset);for(const c of first.clusters){const b=Buffer.alloc(4);fs.readSync(fd,b,0,4,Number(params.fat1Offset)+c*4);assert.equal(b.readUInt32LE(),0);}assert.equal(fat.readFat32File(fd,params,'aguja-profile.json').toString(),'replacement');}finally{fs.closeSync(fd);}
 await assert.rejects(()=>provisioning.prepareWindows({source,output,sha256:digest,capsule:capsule(),protection:{mode:'plain'}}));assert.equal(crypto.createHash('sha256').update(fs.readFileSync(source)).digest('hex'),digest);
 }finally{fs.rmSync(dir,{recursive:true,force:true});}
});
test('FAT long directory entries span clusters and retain unrelated files', {skip:process.platform==='win32'},()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'aguja-lfn-'));try{const source=synthetic(dir);for(let n=0;n<30;n++)fat.writeFat32File(source,'AGUJA_CFG','config-long-filename-'+n+'.json',JSON.stringify({n}));const last=path.join(dir,'last');execFileSync('mcopy',['-i',source+'@@1048576','::/config-long-filename-29.json',last]);assert.equal(JSON.parse(fs.readFileSync(last)).n,29);const fd=fs.openSync(source,'r');try{const part=fat.findGptPartition(fd),params=fat.parseFat32Params(fd,part.offset);assert(provisioning.releaseMarker(source).features.includes('platform-profile-v1'));for(let n=0;n<30;n++)assert.equal(JSON.parse(fat.readFat32File(fd,params,'config-long-filename-'+n+'.json')).n,n);}finally{fs.closeSync(fd);}}finally{fs.rmSync(dir,{recursive:true,force:true});}});

for(const mode of ['plain','encrypted'])test('Windows FAT '+mode+' tailnet prepared image opens in real runtime without losing options',{skip:process.platform==='win32'},async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'aguja-tailnet-fat-'));try{
 const source=synthetic(dir),output=path.join(dir,'private.img'),digest=crypto.createHash('sha256').update(fs.readFileSync(source)).digest('hex'),c=capsule();c.tailscale={enabled:true,auth_key:'SYNTHETIC-TAILNET-KEY',login_server:'https://headscale.example.invalid',hostname:'fixture-rescue',ssh:false,accept_routes:false};
 await provisioning.prepareWindows({source,output,sha256:digest,capsule:c,protection:{mode,passphrase:'SYNTHETIC-UNLOCK'}});
 const raw=execFileSync('mtype',['-i',output+'@@1048576','::/aguja-profile.json']);if(mode==='encrypted')assert(!raw.includes('SYNTHETIC-TAILNET-KEY'));
 const script='import sys,json;sys.path.insert(0,sys.argv[1]);from profile import open_capsule;c=open_capsule(sys.stdin.buffer.read(),"SYNTHETIC-UNLOCK");assert c["tailscale"]==json.loads(sys.argv[2]);assert c["remote"]=={"enabled":False};print("opened")';assert.equal(execFileSync(py,['-I','-c',script,path.resolve(__dirname,'../../runtime'),JSON.stringify(c.tailscale)],{input:raw}).toString().trim(),'opened');
 assert.equal(crypto.createHash('sha256').update(fs.readFileSync(source)).digest('hex'),digest);
 }finally{fs.rmSync(dir,{recursive:true,force:true});}
});
test('Windows old image rejects enabled tailnet before creating output, disabled still works',{skip:process.platform==='win32'},async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'aguja-tailnet-old-'));try{const source=synthetic(dir,{tailnet:false}),output=path.join(dir,'private.img'),digest=crypto.createHash('sha256').update(fs.readFileSync(source)).digest('hex'),c=capsule();c.tailscale={enabled:true,auth_key:'SYNTHETIC-TAILNET-KEY',login_server:'',hostname:'',ssh:false,accept_routes:false};await assert.rejects(()=>provisioning.prepareWindows({source,output,sha256:digest,capsule:c,protection:{mode:'plain'}}),/imagen.*Tailscale/);assert(!fs.existsSync(output));c.tailscale={enabled:false};await provisioning.prepareWindows({source,output,sha256:digest,capsule:c,protection:{mode:'plain'}});assert(fs.existsSync(output));}finally{fs.rmSync(dir,{recursive:true,force:true});}
});
