'use strict';
(async()=>{
 const response=await window.aguja.i18nCatalog();
 if(!response.ok)throw new Error('catalog');
 const catalog=response.catalog,automaticLanguage=response.systemLanguage||navigator.language||response.language;
 let selectedLanguage='auto';try{selectedLanguage=localStorage.getItem('aguja.ui-language')||'auto';}catch{}
 if(selectedLanguage!=='auto'&&!catalog.uiLanguages.some(l=>l.value===selectedLanguage))selectedLanguage='auto';
 const I18n=AgujaI18n.create(catalog,selectedLanguage==='auto'?automaticLanguage:selectedLanguage),t=I18n.t;
 document.documentElement.lang=I18n.language;
 const appLanguage=document.getElementById('app-language');
 for(const language of catalog.uiLanguages){const option=document.createElement('option');option.value=language.value;option.textContent=language.label;appLanguage.append(option);}
 appLanguage.value=selectedLanguage;
 // Initial snapshot covers application-owned markup only, before account/provider
 // responses exist. Refresh never discovers/changes user-controlled data.
 I18n.translateTree(document.body);I18n.translateTree(document.querySelector('title'));
 for(const [id,options]of [['locale-language',catalog.languages],['locale-keyboard',catalog.keyboards]]){const select=document.getElementById(id),old=select.value;select.replaceChildren(...options.map(item=>{const option=document.createElement('option');option.value=item.value;option.textContent=item.label;return option;}));select.value=options.some(item=>item.value===old)?old:options[0].value;}
 await window.aguja.i18nLanguage?.(I18n.language);
const $=id=>document.getElementById(id);
let localeEdited=false;
for(const id of ['locale-language','locale-keyboard','locale-variant'])$(id).addEventListener('change',()=>{localeEdited=true;});
if(window.aguja.importLocale)window.aguja.importLocale().then(r=>{
 if(!r?.ok||localeEdited)return;
 if(r.locale?.language)$('locale-language').value=r.locale.language;
 if(r.locale?.keyboard){$('locale-keyboard').value=r.locale.keyboard;updateLocaleVariants(r.locale.variant||'');}
 $('locale-status').textContent=r.warning?t(r.warning):t('Idioma y teclado importados de este PC.');
 updateSummary();
}).catch(()=>{$('locale-status').textContent=t('No se pudieron detectar los ajustes del PC. Elige idioma y teclado manualmente.');});
$('donate-open').addEventListener('click',()=>{$('donation-dialog').showModal();});
$('donate-link').addEventListener('click',()=>call('donate'));
const namesSource=['Imagen','Conectividad','Acceso SSH','Herramientas IA','Acceso remoto','Crear disco'];
const providers={codex:{name:'Codex',api:'Clave API de OpenAI',note:'Importa la sesión de Codex desde su archivo o almacén nativo de Windows.'},antigravity:{name:'Antigravity',api:'Clave API de Gemini',note:'Importa la sesión OAuth de este usuario desde su archivo o entrada nativa de Windows. No copia otras credenciales, historial ni rutas de este PC.'},claude:{name:'Claude Code',api:'Clave API de Anthropic',note:'La importación comprueba los archivos nativos; no traslada secretos del llavero.'},opencode:{name:'OpenCode',api:'Clave API',note:'Importación del archivo nativo solo cuando es portable.'}};
let step=0,image=null,prepared=null,busy=false,disks=[],providerState={},bitlockerState={available:false,volumes:[],activeVolume:null,cachedKey:null,requiresElevation:false,error:null};
function notice(message,success=false){$('notification').textContent=t(message);$('notification').className=success?'success':'';$('notification').hidden=false;}
function clearNotice(){$('notification').hidden=true;}
function fmt(bytes){return (bytes/1024**3).toFixed(2)+' GiB';}
function showStep(index){if(busy)return;step=index;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',Number(v.dataset.step)===step));document.querySelectorAll('.step').forEach((b,i)=>{b.classList.toggle('active',i===step);b.classList.toggle('done',i<step);});$('back').hidden=step===0;$('next').hidden=step===5;$('step-caption').textContent=[t('Empecemos por la imagen.'),t('Tu red, preparada desde el arranque.'),t('Acceso completo, con tus propias llaves.'),t('La autenticación sigue bajo tu control.'),t('Conexión opcional, revocable y temporal.'),t('La imagen privada contiene tu configuración.')][step];updateSummary();window.scrollTo(0,0);}
function setBusy(value){busy=value;document.querySelectorAll('button').forEach(b=>{b.disabled=value;});updateFlashState();document.querySelectorAll('input,select,textarea').forEach(el=>{el.disabled=value;});updateBitLockerUI();applyProviderState();}
async function call(action,args=[],success){clearNotice();setBusy(true);try{const r=await window.aguja[action](...args);if(!r.ok){notice(r.error);return null;}if(r.canceled)return null;if(success)notice(success,true);return r;}catch{notice(t('No se completó la operación. Puedes volver a intentarlo.'));return null;}finally{setBusy(false);$('progress').hidden=true;}}
function capsule(){const p={};for(const id of Object.keys(providers)){const mode=$('mode-'+id).value;p[id]={mode,api_key:mode==='api'?$('key-'+id).value:'',base_url:mode==='api'?$('url-'+id).value:'',model:mode==='api'?$('model-'+id).value:''};}return {schema:1,hostname:$('hostname').value,locale:{language:$('locale-language').value,keyboard:$('locale-keyboard').value,variant:$('locale-variant').value},network:{ethernet:{method:$('eth-method').value,address:$('eth-address').value,prefix:Number($('eth-prefix').value),gateway:$('eth-gateway').value,dns:$('eth-dns').value.split(',').map(s=>s.trim()).filter(Boolean)},wifi:{ssid:$('wifi-ssid').value,password:$('wifi-password').value,security:$('wifi-security').value,country:$('wifi-country').value.toUpperCase(),hidden:$('wifi-hidden').checked}},ssh:{password:$('ssh-password').value,public_key:$('ssh-key').value.trim(),port:Number($('ssh-port').value)},providers:p,remote:{enabled:false},tailscale:{enabled:Boolean($('tailscale-enabled')?.checked),auth_key:$('tailscale-auth-key')?.value.trim()||'',login_server:$('tailscale-login-server')?.value.trim()||'',hostname:$('tailscale-hostname')?.value.trim()||'',ssh:$('tailscale-ssh')?.checked??false,accept_routes:$('tailscale-accept-routes')?.checked??false}};}
function updateSummary(){const c=capsule();if($('tailscale-connect-example'))$('tailscale-connect-example').textContent=c.ssh.port===22?'ssh aguja@<IP-tailnet>':'ssh -p '+c.ssh.port+' aguja@<IP-tailnet>';const entries=[[t('Imagen'),image?.name||t('Pendiente')],[t('Equipo'),c.hostname],[t('Idioma / teclado'),$('locale-language').selectedOptions[0].textContent+' / '+c.locale.keyboard+(c.locale.variant?' · '+c.locale.variant:'')],[t('Red'),c.network.wifi.ssid?'Wi-Fi + Ethernet':'Ethernet'],['SSH',c.ssh.public_key?t('Clave pública / puerto ')+c.ssh.port:t('Contraseña / puerto ')+c.ssh.port],[t('IA'),Object.entries(c.providers).filter(([,p])=>p.mode!=='none').map(([id])=>providers[id].name).join(', ')||t('Sin preconfigurar')],[t('Red privada'),c.tailscale.enabled?(c.tailscale.login_server?'Headscale':'Tailscale')+' · '+(c.tailscale.hostname||c.hostname):t('Desactivada')]];if(c.tailscale?.enabled){entries.push(['SSH tailnet',c.tailscale.ssh?'Tailscale SSH · requiere políticas':'OpenSSH · puerto '+c.ssh.port]);}if(bitlockerState.available&&bitlockerState.volumes.length>0){const inject=$('bitlocker-inject')?.checked;const vol=bitlockerState.activeVolume;entries.push([t('BitLocker'),inject&&vol?t('Llave a imagen (')+(vol.mountPoint)+')':t('No incluir')]);} $('summary').replaceChildren(...entries.map(([name,value])=>{const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=name;dd.textContent=value;row.append(dt,dd);return row;}));}
function fillProfile(c){localeEdited=true;invalidatePrepared();$('locale-language').value=c.locale?.language||catalog.default.language;$('locale-keyboard').value=c.locale?.keyboard||catalog.default.keyboard;updateLocaleVariants(c.locale?.variant||'');$('hostname').value=c.hostname;$('eth-method').value=c.network.ethernet.method;$('eth-address').value=c.network.ethernet.address||'';$('eth-prefix').value=c.network.ethernet.prefix||24;$('eth-gateway').value=c.network.ethernet.gateway||'';$('eth-dns').value=(c.network.ethernet.dns||[]).join(', ');$('static-fields').hidden=$('eth-method').value!=='manual';const w=c.network.wifi||{};$('wifi-ssid').value=w.ssid||'';$('wifi-password').value=w.password||'';$('wifi-security').value=w.security||'wpa-psk';$('wifi-country').value=w.country||'ES';$('wifi-hidden').checked=Boolean(w.hidden);$('ssh-password').value=c.ssh.password;$('ssh-port').value=c.ssh.port;$('ssh-key').value=c.ssh.public_key;for(const id of Object.keys(providers)){const p=c.providers[id]||{mode:'none'};$('mode-'+id).value=p.mode==='import'?'none':p.mode;$('key-'+id).value=p.api_key||'';$('url-'+id).value=p.base_url||'';$('model-'+id).value=p.model||'';providerMode(id);} const ts=c.tailscale||{};if($('tailscale-enabled')){$('tailscale-enabled').checked=Boolean(ts.enabled);$('tailscale-fields').hidden=!ts.enabled;$('tailscale-auth-key').value=ts.auth_key||'';$('tailscale-login-server').value=ts.login_server||'';$('tailscale-hostname').value=ts.hostname||'';$('tailscale-ssh').checked=ts.ssh??false;$('tailscale-accept-routes').checked=ts.accept_routes??false;}updateSummary();}
function providerMode(id){const mode=$('mode-'+id).value;$('api-'+id).hidden=mode!=='api';$('import-'+id).hidden=mode!=='import';}
for(const [i,name]of namesSource.entries()){const b=document.createElement('button');b.className='step'+(i===0?' active':'');const num=document.createElement('span');num.className='number';num.textContent=String(i+1).padStart(2,'0');const label=document.createElement('span');label.textContent=namesSource[i];b.append(num,label);b.addEventListener('click',()=>showStep(i));$('steps').append(b);I18n.translateTree(b);}
for(const [id,p]of Object.entries(providers)){const card=document.createElement('article');card.className='card';
 // Template values below are static application strings, never returned provider data.
 card.innerHTML=`<div class="provider-head"><h2>${p.name}</h2><span class="badge missing" id="badge-${id}">Comprobando CLI</span></div><div class="button-row"><button id="install-${id}" class="secondary" hidden>Descargar e instalar CLI</button><button id="check-${id}" class="quiet">Volver a comprobar</button><button id="docs-${id}" class="quiet">Guía oficial</button></div><p class="hint">Instalación opcional en este PC para iniciar sesión e importar. El disco de rescate ya incluye las cuatro herramientas; con una clave API no necesitas instalarlas aquí.</p><label for="mode-${id}">Preconfigurar con</label><select id="mode-${id}"><option value="none">Configurar después</option><option value="api">Clave API</option><option value="import">Mi sesión de este equipo</option></select><div id="api-${id}" class="provider-body" hidden><label for="key-${id}">${p.api}</label><div class="secret"><input id="key-${id}" type="password" autocomplete="new-password"><button class="reveal" data-for="key-${id}" aria-label="Mostrar clave API">◉</button></div><label for="url-${id}">Endpoint HTTPS · opcional</label><input id="url-${id}" placeholder="Usar proveedor oficial"><label for="model-${id}">Modelo · opcional</label><input id="model-${id}" placeholder="Elegir al iniciar"></div><div id="import-${id}" class="provider-import" hidden><p class="hint">${p.note}</p><div class="button-row"><button id="login-${id}" class="quiet">Iniciar sesión en este PC</button><button id="import-btn-${id}" class="secondary">Comprobar e importar</button><button id="import-folder-${id}" class="quiet">Seleccionar carpeta del perfil</button></div><p id="import-state-${id}" class="hint">Aún no se ha importado ninguna sesión.</p></div>`;
 $('provider-cards').append(card);I18n.translateTree(card);$('mode-'+id).addEventListener('change',()=>providerMode(id));$('install-'+id).addEventListener('click',async()=>{const r=await call('providerInstall',[id]);await refreshProviders();if(r?.installed)notice(t('CLI instalado. Elige Mi sesión de este equipo, inicia sesión y comprueba la importación.'),true);});$('check-'+id).addEventListener('click',refreshProviders);$('docs-'+id).addEventListener('click',()=>call('providerDocs',[id]));$('login-'+id).addEventListener('click',()=>call('providerLogin',[id],t('Se abrió el CLI oficial. Completa allí tu autorización y después comprueba la importación.')));const importSession=async(selectFolder)=>{const r=await call('importProvider',[id,selectFolder]);invalidatePrepared();await refreshProviders();if(r)$('import-state-'+id).textContent=t(r.summary);else if(!providerState[id]?.imported)$('import-state-'+id).textContent=t('Aún no se ha importado ninguna sesión.');};$('import-btn-'+id).addEventListener('click',()=>importSession(false));$('import-folder-'+id).addEventListener('click',()=>importSession(true));
}
document.addEventListener('click',e=>{const button=e.target.closest('.reveal');if(button){const input=$(button.dataset.for);input.type=input.type==='password'?'text':'password';button.setAttribute('aria-label',input.type==='password'?t('Mostrar secreto'):t('Ocultar secreto'));}});
$('back').addEventListener('click',()=>showStep(step-1));$('next').addEventListener('click',()=>{if(step===0&&!image){notice(t('Selecciona o descarga una imagen antes de continuar.'));return;}showStep(Math.min(5,step+1));});
$('catalog-load').addEventListener('click',async()=>{const r=await call('catalog');if(!r)return;$('releases').replaceChildren(...r.releases.map((release,index)=>{const row=document.createElement('div');row.className='release-row';const title=document.createElement('strong');title.textContent=release.name;const p=document.createElement('p');p.textContent=fmt(release.bytes)+t(' · Firma verificada');const button=document.createElement('button');button.className='primary';button.textContent=t('Descargar ')+release.version;button.addEventListener('click',async()=>{const result=await call('download',[index]);if(result?.image)setImage(result.image);});row.append(title,p,button);return row;}));});
function setImage(i){image=i;prepared=null;$('prepared-status').hidden=true;const status=i.verification==='verified-catalog'?t('Versión oficial ')+i.version+t(' · Firma y SHA-256 verificados'):i.verification==='verified-sha'?t('Imagen local · SHA-256 coincidente con el indicado; origen no comprobado'):t('Imagen local · SHA calculado; origen no comprobado');$('image-status').hidden=false;$('image-status').classList.toggle('local-image',!i.trusted);$('image-status').textContent=i.name+' · '+fmt(i.bytes)+' · '+status;updateSummary();updateFlashState();}
$('image-import').addEventListener('click',async()=>{const r=await call('importImage',[$('image-sha').value.trim().toLowerCase()]);if(r?.image)setImage(r.image);});
$('wifi-import').addEventListener('click',async()=>{const r=await call('importWifi');if(!r?.wifi)return;$('wifi-ssid').value=r.wifi.ssid;$('wifi-password').value=r.wifi.password;$('wifi-security').value=r.wifi.security;$('wifi-hidden').checked=r.wifi.hidden;invalidatePrepared();notice(t('Red activa importada. La contraseña permanece oculta.'),true);});
function updateLocaleVariants(variant='') {
 const keyboard=catalog.keyboards.find(k=>k.value===$('locale-keyboard').value);
 const options=keyboard?.variants||[''];
 $('locale-variant').replaceChildren(...options.map(value=>{const option=document.createElement('option');option.value=value;option.textContent=t(catalog.variants[value]);return option;}));
 $('locale-variant').value=options.includes(variant)?variant:'';
}
$('locale-keyboard').addEventListener('change',()=>updateLocaleVariants());
$('locale-import').addEventListener('click',async()=>{const r=await call('importLocale');if(!r)return;localeEdited=true;if(r.locale.language)$('locale-language').value=r.locale.language;if(r.locale.keyboard){$('locale-keyboard').value=r.locale.keyboard;updateLocaleVariants(r.locale.variant||'');}invalidatePrepared();$('locale-status').textContent=(r.warning?t(r.warning):null)||t('Idioma y teclado importados de este PC.');notice((r.warning?t(r.warning):null)||t('Idioma y teclado importados. Puedes ajustarlos manualmente.'),!r.warning);});
$('eth-method').addEventListener('change',()=>{$('static-fields').hidden=$('eth-method').value!=='manual';});
$('ssh-generate').addEventListener('click',async()=>{const r=await call('generatePassword');if(r){$('ssh-password').value=r.password;invalidatePrepared();notice(t('Contraseña única creada. Puedes verla con el botón del campo y guardarla en tu gestor.'),true);}});
$('tailscale-enabled')?.addEventListener('change',()=>{invalidatePrepared();$('tailscale-fields').hidden=!$('tailscale-enabled').checked;updateSummary();});
$('tailscale-auth-key')?.addEventListener('input',()=>{invalidatePrepared();updateSummary();});
$('tailscale-login-server')?.addEventListener('input',()=>{invalidatePrepared();updateSummary();});
$('tailscale-hostname')?.addEventListener('input',()=>{invalidatePrepared();updateSummary();});
$('tailscale-ssh')?.addEventListener('change',()=>{invalidatePrepared();updateSummary();});
document.querySelectorAll('input[name=protection]').forEach(r=>r.addEventListener('change',()=>{$('unlock-fields').hidden=document.querySelector('input[name=protection]:checked').value!=='encrypted';}));
function preparationInput(){const mode=document.querySelector('input[name=protection]:checked').value;const result={capsule:capsule(),protection:{mode,passphrase:mode==='encrypted'?$('unlock-password').value:''}};if(bitlockerState.available&&$('bitlocker-inject')?.checked&&bitlockerState.cachedKey){result.bitlocker=[bitlockerState.cachedKey];}return result;}
function setPrepared(value){prepared=value;$('prepared-status').hidden=false;$('prepared-status').textContent='✓ '+prepared.name+' · '+fmt(prepared.bytes)+t(' · Lectura SHA-256 verificada. Imagen privada lista.');updateFlashState();}
$('prepare').addEventListener('click',async()=>{if(!image){notice(t('Selecciona primero una imagen.'));return;}if(bitlockerState.available&&$('bitlocker-inject')?.checked&&bitlockerState.activeVolume&&!bitlockerState.cachedKey){if(!await readBitLockerKey())return;}const r=await call('prepare',[preparationInput()]);if(r?.prepared){setPrepared(r.prepared);notice(t('Tu imagen privada está lista. Puedes grabarla cuando elijas un USB.'),true);}});
async function profilePassword(title){$('password-title').textContent=title;$('profile-password').value='';$('password-dialog').showModal();return new Promise(resolve=>$('password-dialog').addEventListener('close',function listener(){this.removeEventListener('close',listener);resolve(this.returnValue==='accept'?$('profile-password').value:null);},{once:true}));}
$('profile-save').addEventListener('click',async()=>{const passphrase=await profilePassword(t('Guardar un perfil cifrado'));if(passphrase!==null)await call('exportProfile',[{capsule:capsule(),passphrase}],t('Perfil cifrado guardado. Las sesiones OAuth importadas se comprobarán de nuevo al crear otra imagen.'));});
$('profile-open').addEventListener('click',async()=>{const passphrase=await profilePassword(t('Abrir un perfil cifrado'));if(passphrase===null)return;const r=await call('importProfile',[passphrase]);if(r?.capsule){fillProfile(r.capsule);notice(t('Perfil cargado. Comprueba de nuevo las sesiones OAuth y la vigencia de tu clave de tailnet.'),true);}});
function updateFlashState(){
 const disk=$('usb-disks').value===''?null:disks[Number($('usb-disks').value)];
 $('flash').disabled=busy||!image||!disk;
 $('flash').textContent=prepared?t('Grabar USB'):t('Preparar y grabar USB');
 $('flash-status').textContent=busy?t('Espera a que termine la operación actual.'):!image?t('Selecciona una imagen en el primer paso.'):!disk?t('Busca y selecciona un USB desmontado.'):image.bytes>disk.size?t('La imagen no cabe en este USB. Elige uno con más capacidad.'):prepared?t('Todo listo. Confirma el USB en la siguiente ventana.'):t('Todo listo: prepararemos tu imagen y grabaremos el USB. ')+($('usb-backup').checked?t('Con respaldo previo.'):t('Se borrará el contenido anterior, sin respaldo.'));
 if(disk&&image?.bytes>disk.size)$('flash').disabled=true;
}
$('disks-refresh').addEventListener('click',async()=>{const r=await call('disks');if(!r)return;disks=r.disks;$('usb-disks').replaceChildren();const blank=document.createElement('option');blank.value='';blank.textContent=disks.length?t('Elige un USB desmontado'):t('No hay USB desmontados disponibles');$('usb-disks').append(blank);for(const [i,d]of disks.entries()){const opt=document.createElement('option');opt.value=i;opt.textContent=d.model+' · '+fmt(d.size)+' · '+d.serial;$('usb-disks').append(opt);}updateFlashState();});
$('usb-disks').addEventListener('change',updateFlashState);
$('usb-backup').addEventListener('change',updateFlashState);
$('flash').addEventListener('click',async()=>{const d=disks[Number($('usb-disks').value)];if(!d||!image)return;if(bitlockerState.available&&$('bitlocker-inject')?.checked&&bitlockerState.activeVolume&&!bitlockerState.cachedKey){if(!await readBitLockerKey())return;}const r=await call('flash',[{device:d.device,serial:d.serial,backup:$('usb-backup').checked,...preparationInput()}]);if(r?.prepared)setPrepared(r.prepared);if(r?.verified)notice(t('USB grabado y lectura verificada.')+(r.backupVerified?t(' El respaldo anterior quedó guardado.'):t(' Grabación directa, sin respaldo.')),true);});
window.aguja.onProgress(p=>{$('progress').hidden=false;const captions={download:t('Descargando la imagen oficial…'),verify:t('Comprobando SHA-256…'),prepare:(p.message?t(p.message):null)||t('Preparando tu imagen privada…'),flash:(p.message?t(p.message):null)||t('Respaldando y grabando…')};$('progress-message').textContent=captions[p.phase]||t('Trabajando…');if(p.total){$('progress-bar').max=p.total;$('progress-bar').value=p.done||0;$('progress-count').textContent=fmt(p.done||0)+' / '+fmt(p.total);}else{$('progress-bar').removeAttribute('value');$('progress-count').textContent='';}});
async function readBitLockerKey(){const vol=bitlockerState.activeVolume;if(!vol||!vol.hasRecoveryPassword)return null;const key=await call('bitlockerKey',[vol.mountPoint]);if(!key||!/^(?:\d{6}-){7}\d{6}$/.test(key.recoveryPassword||''))return null;bitlockerState.cachedKey=key;return key;}
function updateBitLockerUI(){
 if(!bitlockerState.available)return;
 $('bitlocker-check-btn').disabled=busy;
 const vol=bitlockerState.activeVolume;
 if(!vol){
  $('bitlocker-badge').textContent=t(bitlockerState.requiresElevation?'Pendiente de autorización':bitlockerState.error?'No se pudo comprobar BitLocker. Vuelve a intentarlo.':'Sin unidades');
  $('bitlocker-badge').className='badge missing';
  $('bitlocker-vol-status').textContent=t(bitlockerState.error|| (bitlockerState.requiresElevation?'Se necesitan permisos de Windows para consultar BitLocker. Pulsa Comprobar BitLocker y acepta UAC.':'No se detectaron unidades protegidas.'));
  $('bitlocker-suspend-btn').hidden=true;$('bitlocker-resume-btn').hidden=true;$('bitlocker-view-key-btn').disabled=true;$('bitlocker-export-key-btn').disabled=true;$('bitlocker-inject').disabled=true;return;
 }
 const isProtected=vol.protectionStatus==='On';
 $('bitlocker-badge').textContent=isProtected?t('Protegido'):t('Suspendido');$('bitlocker-badge').className=isProtected?'badge':'badge missing';
 const desc=[vol.mountPoint,vol.capacityGB?vol.capacityGB+' GB':'',vol.encryptionMethod,vol.encryptionPercentage+' %',isProtected?t('Protección activada'):t('Protección suspendida')].filter(Boolean).join(' · ');$('bitlocker-vol-status').textContent=desc;
 $('bitlocker-suspend-btn').hidden=!isProtected;$('bitlocker-suspend-btn').disabled=busy;$('bitlocker-resume-btn').hidden=isProtected;$('bitlocker-resume-btn').disabled=busy;
 $('bitlocker-view-key-btn').disabled=busy||!vol.hasRecoveryPassword;$('bitlocker-export-key-btn').disabled=busy||!vol.hasRecoveryPassword;$('bitlocker-inject').disabled=busy||!vol.hasRecoveryPassword;
 if(!vol.hasRecoveryPassword)$('bitlocker-inject').checked=false;
}
async function refreshBitLocker(keepSelected=true,authorize=false){
 if(!bitlockerState.available)return;
 const res=await call('bitlockerStatus',[authorize]);
 $('bitlocker-card').hidden=false;
 bitlockerState.requiresElevation=Boolean(res?.requiresElevation);bitlockerState.error=res?.error||(!res?'No se pudo comprobar BitLocker. Vuelve a intentarlo.':null);
 bitlockerState.volumes=res?.volumes||[];const prevMount=keepSelected?bitlockerState.activeVolume?.mountPoint:null;
 $('bitlocker-volume').replaceChildren();
 if(!bitlockerState.volumes.length){const opt=document.createElement('option');opt.value='';opt.textContent=t(bitlockerState.requiresElevation?'Pendiente de autorización':bitlockerState.error?'No se pudo comprobar BitLocker. Vuelve a intentarlo.':'No se detectaron unidades BitLocker');$('bitlocker-volume').append(opt);bitlockerState.activeVolume=null;bitlockerState.cachedKey=null;updateBitLockerUI();return;}
 for(const v of bitlockerState.volumes){const opt=document.createElement('option');opt.value=v.mountPoint;const prot=v.protectionStatus==='On'?t('Protegido'):t('Suspendido');opt.textContent=`${v.mountPoint} (${v.volumeType==='OperatingSystem'?t('Sistema'):t('Datos')}, ${v.capacityGB} GB · ${prot})`;$('bitlocker-volume').append(opt);}
 $('bitlocker-volume').value=bitlockerState.volumes.some(v=>v.mountPoint===prevMount)?prevMount:bitlockerState.volumes[0].mountPoint;
 bitlockerState.activeVolume=bitlockerState.volumes.find(v=>v.mountPoint===$('bitlocker-volume').value);bitlockerState.cachedKey=null;updateBitLockerUI();updateSummary();
}
$('bitlocker-check-btn').addEventListener('click',()=>refreshBitLocker(true,true));
$('bitlocker-volume').addEventListener('change',()=>{bitlockerState.activeVolume=bitlockerState.volumes.find(v=>v.mountPoint===$('bitlocker-volume').value)||null;bitlockerState.cachedKey=null;updateBitLockerUI();invalidatePrepared();updateSummary();});
$('bitlocker-inject').addEventListener('change',()=>{invalidatePrepared();updateSummary();});
$('bitlocker-suspend-btn').addEventListener('click',async()=>{const vol=bitlockerState.activeVolume;if(!vol)return;const r=await call('bitlockerSuspend',[vol.mountPoint,1],t('BitLocker suspendido en ')+vol.mountPoint+t(' para 1 reinicio.'));if(r){vol.protectionStatus=r.protectionStatus;updateBitLockerUI();}});
$('bitlocker-resume-btn').addEventListener('click',async()=>{const vol=bitlockerState.activeVolume;if(!vol)return;const r=await call('bitlockerResume',[vol.mountPoint],t('Protección de BitLocker reanudada en ')+vol.mountPoint+'.');if(r){vol.protectionStatus=r.protectionStatus;updateBitLockerUI();}});
$('bitlocker-view-key-btn').addEventListener('click',async()=>{const vol=bitlockerState.activeVolume;if(!vol)return;const keyInfo=bitlockerState.cachedKey||await readBitLockerKey();if(!keyInfo)return;bitlockerState.cachedKey=keyInfo;$('bitlocker-dialog-mount').textContent=vol.mountPoint;$('bitlocker-key-display').textContent=keyInfo.recoveryPassword;$('bitlocker-dialog-id').textContent=keyInfo.keyProtectorId||t('Sin ID');$('bitlocker-dialog').showModal();});
$('bitlocker-dialog-copy').addEventListener('click',async()=>{const key=$('bitlocker-key-display').textContent;if(key){try{await navigator.clipboard.writeText(key);notice(t('Clave de recuperación copiada al portapapeles.'),true);}catch{notice(t('No se pudo copiar automáticamente. Puedes copiarla seleccionando el texto.'));}}});
$('bitlocker-export-key-btn').addEventListener('click',async()=>{const vol=bitlockerState.activeVolume;if(!vol)return;const r=await call('bitlockerExportText',[vol.mountPoint]);if(r&&!r.canceled)notice(t('Clave de recuperación guardada en ')+r.path,true);});
window.aguja.info().then(async r=>{if(r.ok){$('version').textContent=r.version;if($('platform-label'))$('platform-label').textContent=r.platform==='win32'?'Windows':r.platform==='darwin'?'macOS':'Linux';if(r.platform==='win32'){$('usb-backup').checked=false;$('usb-backup').disabled=true;$('usb-backup').closest('label').hidden=true;const hint=$('flash-platform-hint');if(hint)hint.textContent=t('Windows solicitará confirmación de administrador (UAC). La aplicación solo graba en unidades USB extraíbles.');}if(r.bitlockerAvailable){bitlockerState.available=true;await refreshBitLocker();}}});
function applyProviderState(){for(const [id,p]of Object.entries(providerState)){$('badge-'+id).textContent=p.imported?t('Importación preparada'):p.installed?t('CLI local disponible'):t('CLI no instalado');$('badge-'+id).className=p.installed||p.imported?'badge':'badge missing';$('install-'+id).hidden=p.installed;$('install-'+id).disabled=busy;$('login-'+id).disabled=busy||!p.installed;}}
async function refreshProviders(){try{const r=await window.aguja.providerStatus();if(!r.ok){notice(r.error);return;}providerState=r.providers;applyProviderState();}catch{notice(t('No se pudo comprobar el CLI. Vuelve a intentarlo.'));}}
refreshProviders();
updateSummary();

function invalidatePrepared(){window.aguja.invalidatePrepared();if(prepared){prepared=null;$('prepared-status').hidden=false;$('prepared-status').textContent=t('La configuración cambió. La imagen se preparará de nuevo al grabar.');}updateSummary();updateFlashState();}
const configSections=[...document.querySelectorAll('.view')].filter(v=>Number(v.dataset.step)>0);for(const section of configSections){section.addEventListener('input',e=>{if(!['usb-disks','usb-backup','share-url','bitlocker-volume','bitlocker-inject'].includes(e.target.id))invalidatePrepared();});section.addEventListener('change',e=>{if(!['usb-disks','usb-backup','share-url','bitlocker-volume','bitlocker-inject'].includes(e.target.id))invalidatePrepared();});}
updateFlashState();

appLanguage.addEventListener('change',async()=>{
 selectedLanguage=appLanguage.value;
 try{localStorage.setItem('aguja.ui-language',selectedLanguage);}catch{}
 I18n.setLanguage(selectedLanguage==='auto'?automaticLanguage:selectedLanguage);
 await window.aguja.i18nLanguage?.(I18n.language);
 document.documentElement.lang=I18n.language;
 I18n.refresh();updateLocaleVariants($('locale-variant').value);showStep(step);updateSummary();updateFlashState();
});
document.documentElement.lang=I18n.language;
updateLocaleVariants();
})().catch(()=>{const notification=document.getElementById('notification');notification.textContent='Unable to load language settings. Restart LA AGUJA Flash Imager.';notification.hidden=false;});
